services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=prismauser
      - POSTGRES_PASSWORD=prismapassword
      - POSTGRES_DB=prismadb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local